# Generated by Django 3.1.5 on 2021-02-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_menu', models.CharField(max_length=100)),
                ('img_menu', models.ImageField(blank=True, null=True, upload_to='media')),
                ('cat_menu', models.CharField(max_length=100)),
                ('price_menu', models.DecimalField(decimal_places=0, max_digits=6)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
